server:
  port: 8081
  servlet:
    context-path: /breezewind
spring:
  datasource:
    username: root
    password: 996895
    url: jdbc:mysql://www.wtyoha.cn:3306/miaosha_system
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    addresses: www.wtyoha.cn
    port: 5672
    username: wtyoha
    password: 996895
    virtual-host: /

  http:
    encoding:
      force: true #是否将编码强制到HTTP请求和响应上配置的字符集。默认为false
      enabled: true #是否启用http编码支持。默认为false
      charset: UTF-8 #HTTP请求和响应的字符集。如果没有明确设置,就将该字符集添加到Content-Type中

# 静态资源配置
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
    add-mappings: true
    cache:
      period: 1
    chain:
      cache: true
      enabled: true
      html-application-cache: true


# redis
redis:
  host: www.wtyoha.cn
  port: 6379
  timeout: 1000
  password: 996895
  poolMaxTotal: 5000
  poolMaxIdle: 1000
  poolMaxWait: 1000

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 日志
logging:
  level:
    root: info


